server:
   port: 9093
   
cloud:
   aws:
      region:
         static: us-east-1
         auto: false
      credentials:
         access-key: xxxx
         secret-key: xxx
      end-point:
         uri: https://sqs.us-east-1.amazonaws.com/xxxx/netsurfingzone-first-sqs


