server:
   port: 9091
   
cloud:
   aws:
      region:
         static: us-east-1
         auto: false
      credentials:
         access-key: xx
         secret-key: xx
      end-point:
         uri: https://sqs.us-east-1.amazonaws.com/xx/netsurfingzone-first-sqs


